#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:xin/betterlife/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: xin.betterlife.**.entity

#swagger扫描路径配置
swagger:
  base-packages:
    - xin.betterlife

